name: Build Audiveris CLI (Portable JAR, No GUI)

on:
  workflow_dispatch:

jobs:
  build-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build only CLI module (no GUI)
        run: |
          mvn -pl audiveris-cli -am clean package -DskipTests
          mkdir -p output
          cp audiveris-cli/target/*with-dependencies.jar output/audiveris-cli.jar

      - name: Upload CLI JAR
        uses: actions/upload-artifact@v4
        with:
          name: audiveris-cli
          path: output/audiveris-cli.jar
