name: Build Audiveris CLI (ARM-friendly, No GUI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build CLI with dependencies
        run: |
          mvn clean install -DskipTests -Pcli
          mkdir -p output
          cp audiveris-cli/target/*with-dependencies.jar output/audiveris-cli.jar

      - name: Upload Audiveris CLI jar
        uses: actions/upload-artifact@v3
        with:
          name: audiveris-cli
          path: output/audiveris-cli.jar
